version: '3'

services:
  mysql:
    container_name: c-mysql
    image: mysql:8.0.33
    volumes:
      - ./mysqlDB:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - 3306:3306
